### ISSUE TITLE
Clean run gives IllegalAccessError warning

### ISSUE THREAD

**Issue by ksclarke** [vert-x3/vertx-scala.g8#7]
Observation:

I checked out the project for the first time and ran `sbt assembly`. I see the tests pass but then there is a warning log (reproduced below):
```
[info] All tests passed.
[info] Strategy 'discard' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'last' was applied to 4 files (Run the task at debug level to see details)
[success] Total time: 19 s, completed May 29, 2020 12:25:55 PM
[warn] Thread[Thread-6,5,main] loading io.vertx.core.file.impl.FileSystemImpl$11 after test or run has completed. This is a likely resource leak
Exception in thread "Thread-6" Exception in thread "Thread-5" java.lang.IllegalAccessError: tried to access class io.vertx.core.file.impl.FileSystemImpl$11 from class io.vertx.core.file.impl.FileSystemImpl
        at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:699)
        at io.vertx.core.file.impl.FileResolver.deleteCacheDir(FileResolver.java:364)
	at io.vertx.core.file.impl.FileResolver.lambda$null$0(FileResolver.java:340)
	at java.lang.Thread.run(Thread.java:748)
	at io.vertx.core.file.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:344)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalAccessError: io/vertx/core/file/impl/FileSystemImpl$11
	at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:699)
	at io.vertx.core.file.impl.FileResolver.deleteCacheDir(FileResolver.java:364)
	at io.vertx.core.file.impl.FileResolver.lambda$null$0(FileResolver.java:340)
	at java.lang.Thread.run(Thread.java:748)
	at io.vertx.core.file.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:344)
	at java.lang.Thread.run(Thread.java:748)
```
### Version

Latest code from GitHub vertx-scala.g8

### Context

I pulled the repo for the first time and ran `sbt assembly` to test. I saw the tests pass successfully and then received the warning.

### Extra

* Using Ubuntu/PopOS 20.04. I tried with JDK 11 and 8 (to the same result).

**Comment by codepitbull** [comment]
Thanks for reporting, I will take care of this.

**Comment by codepitbull** [comment]
Thanks for reporting, fixed it.
